import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// !CONFIG_UPDATE - Update according to your project needs

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

// WARNING: Be cautious when modifying the main layout.
// Changes here affect all pages in the application.
const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
